/*
 Genesis Supabase configuration.
 This uses the public/publishable Supabase key.
 NEVER place a secret/service_role key in this file.
*/
window.GENESIS_BACKEND = {
  url: "https://yubpnkcsjuxuczrafmmj.supabase.co",
  anonKey: "sb_publishable_JNxkxsQxxy5gwawUduiFbw_wHYsaQ5V"
};

/*
 Genesis VM uses the Windows Genesis Host app.

 The Host app runs GeForce NOW on the host PC and streams only that window to
 Genesis over WebRTC. Supabase Realtime is used only for offer/answer/ICE
 signaling; the video/audio stream itself is peer-to-peer.

 The long random Host Key generated by Genesis Host is the pairing credential.
 Genesis already controls who can see VM through its normal Admin role, so VM
 does not ask for a second Admin password.
*/
window.GENESIS_VM = {
  ...(window.GENESIS_VM || {}),
  provider: "Genesis Host",
  mode: "host",
  sessionEndpoint: "",
  viewerUrl: "",
  startupUrl: "https://play.geforcenow.com/",
  sessionMode: "persistent",
  displayMode: "embed",
  build: "host-webrtc-r3"
};

(function loadGenesisAdminVm(){
  const BUILD = "host-webrtc-r3";

  function currentRole(){
    try{
      const login = JSON.parse(localStorage.getItem("genesisLogin") || "null");
      if(login && login.expires > Date.now()) return String(login.role || "user").toLowerCase();
    }catch{}
    return String(sessionStorage.getItem("genesisRole") || "user").toLowerCase();
  }

  function addFreshScript(src, marker){
    return new Promise((resolve,reject)=>{
      const old = document.querySelector(`script[data-${marker}]`);
      if(old) old.remove();

      const script = document.createElement("script");
      const separator = src.includes("?") ? "&" : "?";
      script.src = `${src}${separator}build=${encodeURIComponent(BUILD)}`;
      script.async = false;
      script.setAttribute(`data-${marker}`, "1");
      script.onload = ()=>resolve();
      script.onerror = ()=>reject(new Error(`Could not load ${src}`));
      document.head.appendChild(script);
    });
  }

  function showHostLoading(){
    const status=document.getElementById("genesisVmStatus");
    if(status) status.textContent="Loading Genesis Host…";
    const overlay=document.getElementById("genesisVmOverlay");
    const card=document.getElementById("genesisVmCard");
    if(overlay&&card){
      card.innerHTML='<div class="genesis-vm-spinner"></div><p>Loading Genesis Host…</p>';
      overlay.classList.remove("hidden");
    }
  }

  function installHostGuard(){
    const vm=window.GenesisVM;
    if(!vm || vm.__hostPatched || vm.__hostGuarded) return;
    vm.__hostGuarded=true;

    // Never let host mode fall back to the generic iframe VM. That path can
    // report "Connected · virtual computer" while displaying only a blank
    // iframe. Until genesis-host-vm.js finishes loading, VM simply waits.
    vm.connect=()=>showHostLoading();
    vm.launch=()=>{
      try{
        if(typeof openApp==="function" && !(typeof openWindows==="object" && openWindows.vm)) openApp("vm");
        else if(typeof openWindows==="object" && openWindows.vm) focusWindow?.(openWindows.vm);
      }catch{}
      setTimeout(showHostLoading,0);
    };
    vm.mount=()=>showHostLoading();
  }

  async function waitForHostPatch(timeoutMs=8000){
    const started=Date.now();
    while(Date.now()-started<timeoutMs){
      if(window.GenesisHostVM?.patch){
        window.GenesisHostVM.patch();
        if(window.GenesisVM?.__hostPatched) return true;
      }
      await new Promise(resolve=>setTimeout(resolve,50));
    }
    return false;
  }

  async function load(){
    if(!/(?:^|\/)os\.html$/i.test(location.pathname)) return;
    if(currentRole() !== "admin") return;

    try{
      // Always request the current build instead of trusting a previously
      // cached VM script. GitHub Pages/browser caches were leaving some users
      // on the old generic iframe implementation after an update.
      await addFreshScript("genesis-vm.js","genesis-vm-host-r3");
      installHostGuard();
      await addFreshScript("genesis-host-vm.js","genesis-host-vm-host-r3");

      const patched=await waitForHostPatch();
      if(!patched) throw new Error("Genesis Host WebRTC module did not attach to VM.");

      window.GenesisVM?.install?.();
      console.info("Genesis VM ready:",BUILD,"Host WebRTC attached");
    }catch(error){
      console.error("Genesis VM could not load:",error);
      const status=document.getElementById("genesisVmStatus");
      if(status) status.textContent="Genesis Host module failed to load";
    }
  }

  if(document.readyState === "complete") load();
  else window.addEventListener("load",load,{once:true});
})();
