/*
 Genesis Supabase configuration.
 This uses the public/publishable Supabase key.
 NEVER place a secret/service_role key in this file.
*/
window.GENESIS_BACKEND = {
  url: "https://yubpnkcsjuxuczrafmmj.supabase.co",
  anonKey: "sb_publishable_JNxkxsQxxy5gwawUduiFbw_wHYsaQ5V"
};

/*
 Genesis VM now supports the Windows Genesis Host app.

 The Host app runs GeForce NOW on the host PC and streams only that window to
 an authenticated Genesis Admin over WebRTC. Supabase Realtime is used only
 for offer/answer/ICE signaling; the video/audio stream is peer-to-peer.

 Pairing is done with a long random Host Key generated by Genesis Host. The
 key is stored locally in the admin's browser and can be regenerated from the
 Host app at any time.
*/
window.GENESIS_VM = window.GENESIS_VM || {
  provider: "Genesis Host",
  mode: "host",
  sessionEndpoint: "",
  viewerUrl: "",
  startupUrl: "https://play.geforcenow.com/",
  sessionMode: "persistent",
  displayMode: "embed"
};

(function loadGenesisAdminVm(){
  function currentRole(){
    try{
      const login = JSON.parse(localStorage.getItem("genesisLogin") || "null");
      if(login && login.expires > Date.now()) return String(login.role || "user").toLowerCase();
    }catch{}
    return String(sessionStorage.getItem("genesisRole") || "user").toLowerCase();
  }

  function addScript(src, marker){
    return new Promise((resolve,reject)=>{
      if(document.querySelector(`script[data-${marker}]`)){resolve();return}
      const script=document.createElement("script");
      script.src=src;
      script.defer=true;
      script.setAttribute(`data-${marker}`,"1");
      script.onload=()=>resolve();
      script.onerror=()=>reject(new Error(`Could not load ${src}`));
      document.head.appendChild(script);
    });
  }

  async function load(){
    if(!/(?:^|\/)os\.html$/i.test(location.pathname)) return;
    if(currentRole() !== "admin") return;
    try{
      if(!window.GenesisVM) await addScript("genesis-vm.js","genesis-vm");
      await addScript("genesis-host-vm.js","genesis-host-vm");
      window.GenesisHostVM?.patch?.();
      window.GenesisVM?.install?.();
    }catch(error){
      console.error("Genesis VM could not load:",error);
    }
  }

  if(document.readyState === "complete") load();
  else window.addEventListener("load",load,{once:true});
})();
