-- ============================================================
-- Genesis global announcements + 3-digit device IDs + DeactivateOS
-- Run this entire file once in Supabase -> SQL Editor.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.genesis_devices (
  id bigint generated by default as identity primary key,
  device_token uuid not null unique,
  display_id smallint not null unique check (display_id between 100 and 999),
  active boolean not null default true,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

create table if not exists public.genesis_announcements (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 2000),
  duration_ms integer not null default 7000 check (duration_ms between 3000 and 30000),
  created_at timestamptz not null default now(),
  created_by text not null default 'Admin'
);

create table if not exists public.genesis_admin_actions (
  id bigint generated by default as identity primary key,
  display_id smallint not null,
  action text not null check (action in ('deactivated','reactivated')),
  created_at timestamptz not null default now(),
  actor text not null default 'Admin'
);

alter table public.genesis_devices enable row level security;
alter table public.genesis_announcements enable row level security;
alter table public.genesis_admin_actions enable row level security;

-- Everyone may read announcements. Only the authenticated Genesis admin may post.
drop policy if exists "genesis public announcements read" on public.genesis_announcements;
create policy "genesis public announcements read"
on public.genesis_announcements
for select
to anon, authenticated
using (true);

drop policy if exists "genesis admin announcements insert" on public.genesis_announcements;
create policy "genesis admin announcements insert"
on public.genesis_announcements
for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'admin@genesisos.lol');

-- Only the authenticated Genesis admin may directly view device/admin history tables.
drop policy if exists "genesis admin devices read" on public.genesis_devices;
create policy "genesis admin devices read"
on public.genesis_devices
for select
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@genesisos.lol');

drop policy if exists "genesis admin actions read" on public.genesis_admin_actions;
create policy "genesis admin actions read"
on public.genesis_admin_actions
for select
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@genesisos.lol');

-- Public-safe RPC: creates/returns one 3-digit ID for this browser token.
create or replace function public.genesis_register_device(p_token uuid)
returns table(display_id smallint, active boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_display_id smallint;
  v_active boolean;
  candidate integer;
  tries integer := 0;
begin
  select d.display_id, d.active
    into v_display_id, v_active
  from public.genesis_devices d
  where d.device_token = p_token;

  if found then
    update public.genesis_devices
       set last_seen = now()
     where device_token = p_token
       and last_seen < now() - interval '30 seconds';

    return query select v_display_id, v_active;
    return;
  end if;

  loop
    tries := tries + 1;
    if tries > 1500 then
      raise exception 'No Genesis 3-digit IDs are available';
    end if;

    candidate := floor(random() * 900 + 100)::integer;

    begin
      insert into public.genesis_devices(device_token, display_id)
      values (p_token, candidate::smallint);

      return query select candidate::smallint, true;
      return;
    exception when unique_violation then
      -- Try another three-digit number.
    end;
  end loop;
end;
$$;

-- Public-safe RPC: check whether this browser ID is still active.
create or replace function public.genesis_check_device(p_token uuid)
returns table(display_id smallint, active boolean)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.genesis_devices
     set last_seen = now()
   where device_token = p_token
     and last_seen < now() - interval '30 seconds';

  return query
    select d.display_id, d.active
    from public.genesis_devices d
    where d.device_token = p_token;
end;
$$;

-- Admin-only RPC: deactivate/reactivate an ID and log the action.
create or replace function public.genesis_set_device_status(
  p_display_id smallint,
  p_active boolean
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  changed integer;
begin
  if coalesce(auth.jwt() ->> 'email','') <> 'admin@genesisos.lol' then
    raise exception 'Admin access required';
  end if;

  update public.genesis_devices
     set active = p_active
   where display_id = p_display_id;

  get diagnostics changed = row_count;

  if changed = 0 then
    raise exception 'Genesis ID % was not found', p_display_id;
  end if;

  insert into public.genesis_admin_actions(display_id, action, actor)
  values (
    p_display_id,
    case when p_active then 'reactivated' else 'deactivated' end,
    'Admin'
  );

  return true;
end;
$$;

revoke all on function public.genesis_register_device(uuid) from public;
revoke all on function public.genesis_check_device(uuid) from public;
revoke all on function public.genesis_set_device_status(smallint, boolean) from public;

grant execute on function public.genesis_register_device(uuid) to anon, authenticated;
grant execute on function public.genesis_check_device(uuid) to anon, authenticated;
grant execute on function public.genesis_set_device_status(smallint, boolean) to authenticated;

grant select on public.genesis_announcements to anon, authenticated;
grant insert on public.genesis_announcements to authenticated;
grant select on public.genesis_devices to authenticated;
grant select on public.genesis_admin_actions to authenticated;
