/*
 Genesis Supabase configuration.
 This uses the public/publishable Supabase key.
 NEVER place a secret/service_role key in this file.
*/
window.GENESIS_BACKEND = {
  url: "https://yubpnkcsjuxuczrafmmj.supabase.co",
  anonKey: "sb_publishable_JNxkxsQxxy5gwawUduiFbw_wHYsaQ5V"
};

/*
 Genesis VM uses the Windows Genesis Host app.

 The Host app runs GeForce NOW on the host PC and streams only that window to
 Genesis over WebRTC. Supabase Realtime is used only for offer/answer/ICE
 signaling; the video/audio stream itself is peer-to-peer.

 The long random Host Key generated by Genesis Host is the pairing credential.
 Genesis already controls who can see VM through its normal Admin role, so VM
 does not ask for a second Admin password.
*/
window.GENESIS_VM = {
  ...(window.GENESIS_VM || {}),
  provider: "Genesis Host",
  mode: "host",
  sessionEndpoint: "",
  viewerUrl: "",
  startupUrl: "https://play.geforcenow.com/",
  sessionMode: "persistent",
  displayMode: "embed",
  build: "host-webrtc-r5"
};

(function loadGenesisAdminVm(){
  const BUILD = "host-webrtc-r5";
  let loading=false;
  let ready=false;

  function currentRole(){
    try{if(typeof genesisRole==="function")return String(genesisRole()||"user").toLowerCase()}catch{}
    try{
      const login = JSON.parse(localStorage.getItem("genesisLogin") || "null");
      if(login && login.expires > Date.now()) return String(login.role || "user").toLowerCase();
    }catch{}
    return "user";
  }

  function addFreshScript(src, marker){
    return new Promise((resolve,reject)=>{
      const old = document.querySelector(`script[data-${marker}]`);
      if(old) old.remove();

      const script = document.createElement("script");
      let settled=false;
      const timeout=setTimeout(()=>finish(new Error(`Loading ${src} timed out.`)),12000);
      function finish(error){
        if(settled)return;settled=true;
        clearTimeout(timeout);script.onload=null;script.onerror=null;
        if(error){script.remove();reject(error)}else resolve();
      }
      const separator = src.includes("?") ? "&" : "?";
      script.src = `${src}${separator}build=${encodeURIComponent(BUILD)}`;
      script.async = false;
      script.setAttribute(`data-${marker}`, "1");
      script.onload = ()=>finish();
      script.onerror = ()=>finish(new Error(`Could not load ${src}`));
      document.head.appendChild(script);
    });
  }

  function showHostLoading(){
    // A queued guard callback must not overwrite the pairing/stream screen
    // after the real Host module has already attached.
    if(window.GenesisVM?.__hostPatched)return;
    const status=document.getElementById("genesisVmStatus");
    if(status) status.textContent="Loading Genesis Host…";
    const overlay=document.getElementById("genesisVmOverlay");
    const card=document.getElementById("genesisVmCard");
    if(overlay&&card){
      card.innerHTML='<div class="genesis-vm-spinner"></div><p>Loading Genesis Host…</p>';
      overlay.classList.remove("hidden");
    }
  }

  function installHostGuard(){
    const vm=window.GenesisVM;
    if(!vm || vm.__hostPatched || vm.__hostGuarded) return;
    vm.__hostGuarded=true;

    // Never let host mode fall back to the generic iframe VM. That path can
    // report "Connected · virtual computer" while displaying only a blank
    // iframe. Until genesis-host-vm.js finishes loading, VM simply waits.
    vm.connect=()=>showHostLoading();
    vm.launch=()=>{
      try{
        if(typeof openApp==="function" && !(typeof openWindows==="object" && openWindows.vm)) openApp("vm");
        else if(typeof openWindows==="object" && openWindows.vm) focusWindow?.(openWindows.vm);
      }catch{}
      setTimeout(showHostLoading,0);
    };
    vm.mount=()=>showHostLoading();
  }

  async function waitForHostPatch(timeoutMs=8000){
    const started=Date.now();
    while(Date.now()-started<timeoutMs){
      if(window.GenesisHostVM?.patch){
        window.GenesisHostVM.patch();
        if(window.GenesisVM?.__hostPatched) return true;
      }
      await new Promise(resolve=>setTimeout(resolve,50));
    }
    return false;
  }

  async function load(){
    if(!/(?:^|\/)os\.html$/i.test(location.pathname)) return;
    if(currentRole() !== "admin") return;
    if(ready&&window.GenesisVM?.__hostPatched){window.GenesisVM.install?.();return}
    if(loading)return;
    loading=true;

    try{
      // Always request the current build instead of trusting a previously
      // cached VM script. GitHub Pages/browser caches were leaving some users
      // on the old generic iframe implementation after an update.
      if(!window.GenesisVM)await addFreshScript("genesis-vm.js","genesis-vm-host-r5");
      installHostGuard();
      await addFreshScript("genesis-host-vm.js","genesis-host-vm-host-r5");

      const patched=await waitForHostPatch();
      if(!patched) throw new Error("Genesis Host WebRTC module did not attach to VM.");

      window.GenesisVM?.install?.();
      ready=true;
      // A user may open VM while the Host script is still downloading. Resume
      // that already-open window instead of leaving its loading guard forever.
      if(document.getElementById("genesisVmRoot"))window.GenesisVM?.mount?.();
      console.info("Genesis VM ready:",BUILD,"Host WebRTC attached");
    }catch(error){
      console.error("Genesis VM could not load:",error);
      const status=document.getElementById("genesisVmStatus");
      if(status) status.textContent="Genesis Host module failed to load";
      const card=document.getElementById("genesisVmCard"),overlay=document.getElementById("genesisVmOverlay");
      if(card&&overlay){
        card.innerHTML='<h2>Host module unavailable</h2><p>Genesis could not load the Host connection. Retry to download it again.</p><button type="button" class="genesis-vm-button" onclick="GenesisHostLoader.retry()">Retry loading</button>';
        overlay.classList.remove("hidden");
      }
    }finally{
      loading=false;
    }
  }

  window.GenesisHostLoader={retry:load,build:BUILD};
  // The OS app table exists after parsing. Waiting for window.load also waits
  // for every image/frame and could leave VM absent when one resource stalls.
  if(document.readyState === "loading") document.addEventListener("DOMContentLoaded",load,{once:true});
  else load();
})();
