import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import vm from "node:vm";

const egg=readFileSync(new URL("../genesis-ransom-easter.js",import.meta.url),"utf8");
function memoryStorage(seed={}){const map=new Map(Object.entries(seed));return {getItem:key=>map.has(key)?map.get(key):null,setItem:(key,value)=>map.set(key,String(value)),removeItem:key=>map.delete(key)}}
function load({username="ransom",password="ransom"}={}){const listeners=[];const doc={readyState:"loading",documentElement:{classList:{add(){},remove(){}}},head:{appendChild(){}},body:{appendChild(){}},createElement:()=>({textContent:"",style:{},classList:{add(){},remove(){},contains(){return false}},appendChild(){},addEventListener(){},querySelector(){return null}}),addEventListener:(...args)=>listeners.push(args),getElementById:id=>id==="username"?{value:username}:id==="password"?{value:password}:null};const scope={document:doc,globalThis:null,window:null,location:{pathname:"/index.html",search:"",href:"https://genesis.example/index.html"},localStorage:memoryStorage(),sessionStorage:memoryStorage(),URL,URLSearchParams,setTimeout,clearTimeout,setInterval,clearInterval,Date,Math,console,Audio:function(){}};scope.window=scope;scope.globalThis=scope;vm.runInNewContext(egg,scope,{filename:"genesis-ransom-easter.js"});return scope.GenesisRansomEaster}

test("RANSOM login trigger remains ransom/ransom",()=>{assert.equal(load().credentialsMatch(),true);assert.equal(load({password:"nope"}).credentialsMatch(),false)});
test("RANSOM uses local media and the exact 63 second coin rules",()=>{assert.match(egg,/tapeZero:"assets\/ransom\/tape-zero\.mp4"/);assert.match(egg,/jumpscare:"assets\/ransom\/jumpscare\.mp4"/);assert.match(egg,/encrypted:"assets\/ransom\/encrypted\.mp3"/);assert.match(egg,/coinSound:"assets\/ransom\/coins\.mp3"/);assert.match(egg,/thankYouSound:"assets\/ransom\/thank-you\.mp3"/);assert.match(egg,/GAME_DURATION_MS=63_000/);assert.match(egg,/COIN_COUNT=5/);assert.match(egg,/COIN_VALUE=100/)});
test("intro plays directly with no warning exit or YouTube UI",()=>{assert.doesNotMatch(egg,/SAFE GAME SIMULATION|PLAY TAPE ZERO|TAPE ZERO · LOCAL VIDEO|data-ransom-exit|youtube\.com|youtu\.be/i);assert.match(egg,/ransom-intro-glitching/);assert.match(egg,/ransom-transition-noise/)});
test("RANSOM stays over the real OS and supplied windows are movable",()=>{assert.match(egg,/genesis-ransom-os-layer/);assert.match(egg,/background:transparent/);assert.doesNotMatch(egg,/ransom-static-backdrop/);assert.match(egg,/const variants=\["skull","purpleVertical","redStatic","purpleHorizontal"\]/);assert.match(egg,/makeDraggable/);assert.match(egg,/cycleMainWindow/);assert.match(egg,/ransom-os-window/)});
test("locked apps use the supplied stop hand and coins fly to the main counter",()=>{assert.match(egg,/img\.src=asset\("stopHand"\)/);assert.match(egg,/flyCoinsToMain/);assert.match(egg,/ransom-fly-coin/);assert.match(egg,/for\(let i=0;i<3;i\+\+\)/)});
test("failure uses a muted A-90 video while ENCRYPTED music keeps playing",()=>{assert.match(egg,/video\.src=asset\("jumpscare"\)/);assert.match(egg,/video\.muted=true/);assert.match(egg,/video\.addEventListener\("ended",closeJump/);const failure=egg.slice(egg.indexOf("function finishFailure"),egg.indexOf("function stopEvent"));assert.doesNotMatch(failure,/state\.music\?\.pause|clearTimers\(state\)/)});
test("Glitch Store reward is removed from the RANSOM event",()=>{assert.doesNotMatch(egg,/GLITCH_UNLOCK_KEY|Glitch is unlocked|genesisRansomGlitchUnlocked/)});
test("RANSOM code has no destructive file or encryption operations",()=>{assert.doesNotMatch(egg,/crypto\.subtle\.encrypt|rmSync|unlinkSync|writeFileSync|XMLHttpRequest|fetch\s*\(/i)});
